### ISSUE TITLE
Card hovering error

### ISSUE THREAD

**Issue by huhjiwon** [3billion/3billion.github.io#5]
![2017-04-28 11 33 53](https://cloud.githubusercontent.com/assets/28091169/25512158/a0b47f1a-2c06-11e7-8aba-26fba4e626b5.png)

카드 마우스오버시, 제가 지정한 적이 없는 그린 컬러 그라데이션이 나옵니다.
조금 부자연스럽게 느껴지고요, 심플해 보이진 않는 것 같아요.

그냥 모든 텍스트가 레드 컬러가 되는 방식으로 해주세요.

**Comment by graphy21** [comment]
수정했습니다.
